version: "3.3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./black-eyes:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.uk.rule=Host(`vpn.wuhanstudio.uk`)"
        - "traefik.http.routers.uk.entrypoints=web"
        - "traefik.http.services.uk.loadbalancer.server.port=80"
        # TLS
        - "traefik.http.routers.uks.rule=Host(`vpn.wuhanstudio.uk`)"
        - "traefik.http.routers.uks.entrypoints=websecure"
        - "traefik.http.routers.uks.tls.certresolver=myhttpchallenge"
        # Redirect
        - "traefik.http.routers.uk.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
