version: "3.3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./bookshelf:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/defaul.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cn.rule=Host(`vpn.wuhanstudio.cn`)"
        - "traefik.http.routers.cn.entrypoints=web"
        - "traefik.http.services.cn.loadbalancer.server.port=80"
        # TLS
        - "traefik.http.routers.cns.rule=Host(`vpn.wuhanstudio.cn`)"
        - "traefik.http.routers.cns.entrypoints=websecure"
        - "traefik.http.routers.cns.tls.certresolver=myhttpchallenge"
        # Redirect
        - "traefik.http.routers.cn.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
